name: Test Backend

on:
  push:
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: Run tests
        working-directory: backend
        run: go test -cover ./...
